name       : libayatana-appindicator
version    : 0.5.5
release    : 1
source     :
    - https://github.com/AyatanaIndicators/libayatana-appindicator/archive/refs/tags/0.5.5.tar.gz : 55e47e94f54e6f2f13bcc06ab20530ad0a1412282a8775331af41788b59ee331
license    :
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  : programming.library
summary    : Application Indicator Library. Spiritual successor of libappindicator
description: |
    A library to allow applications to export a menu into the an Application Indicators aware menu bar. Based on KSNI it also works in KDE and will fallback to generic Systray support if none of those are available.
    This code project was originally started by Canonical Ltd. and has been adapted by various authors with the purpose of making this Application Indicators available on Ubuntu and non-Ubuntu systems alike.
builddeps  :
    - pkgconfig32(ayatana-indicator-0.4)
    - pkgconfig32(ayatana-indicator3-0.4)
    - pkgconfig32(dbus-glib-1)
    - pkgconfig32(dbusmenu-gtk-0.4)
    - gtk-doc
    - mate-common
    - vala
replaces   :
    - libappindicator
    - devel : libappindicator-devel
    - 32bit : libappindicator-32bit
    - 32bit-devel : libappindicator-32bit-devel
emul32     : yes
setup      : |
    NOCONFIGURE=1 ./autogen.sh
    mkdir gtk2
    pushd gtk2
        ../configure --disable-static --disable-tests %CONFOPTS% --with-gtk=2
    popd
    mkdir gtk3
    pushd gtk3
        ../configure --disable-static --disable-tests %CONFOPTS% --with-gtk=3
    popd
build      : |
    %make -C gtk2
    %make -C gtk3
install    : |
    %make_install -j1 -C gtk2
    %make_install -j1 -C gtk3

    # libayatana provides ABI compatibility with libappindicator.
    # Create symlinks with libappindicator's sonames so that closed-source
    # applications built for libappindicator can continue to work.
    pushd $installdir/%libdir%
        for f in *.so*; do
            ln -s $f $(sed 's|ayatana-||' <<< $f)
        done
    popd
