name       : libayatana-appindicator
version    : 0.5.92
release    : 2
source     :
    - https://github.com/AyatanaIndicators/libayatana-appindicator/archive/refs/tags/0.5.92.tar.gz : adedcf160dae7547971d475b42062cab278d54ec075537e6958ffdbf2d996857
license    :
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  : programming.library
summary    : Application Indicator Library. Spiritual successor of libappindicator
description: |
    A library to allow applications to export a menu into the an Application Indicators aware menu bar. Based on KSNI it also works in KDE and will fallback to generic Systray support if none of those are available.
    This code project was originally started by Canonical Ltd. and has been adapted by various authors with the purpose of making this Application Indicators available on Ubuntu and non-Ubuntu systems alike.
builddeps  :
    - pkgconfig32(ayatana-indicator-0.4)
    - pkgconfig32(ayatana-indicator3-0.4)
    - pkgconfig32(dbus-glib-1)
    - pkgconfig32(dbusmenu-gtk-0.4)
    - gtk-doc
    - mate-common
    - vala
replaces   :
    - libappindicator
    - devel : libappindicator-devel
    - 32bit : libappindicator-32bit
    - 32bit-devel : libappindicator-32bit-devel
emul32     : yes
setup      : |
    mkdir gtk3
    pushd gtk3
        %cmake_ninja ../ -DCMAKE_INSTALL_LIBDIR=%libdir% -DENABLE_BINDINGS_MONO=OFF -DENABLE_BINDINGS_VALA=ON -DFLAVOUR_GTK3=ON -DFLAVOUR_GTK2=OFF
    popd
    mkdir gtk2
    pushd gtk2
        %cmake_ninja ../ -DCMAKE_INSTALL_LIBDIR=%libdir% -DENABLE_BINDINGS_MONO=OFF -DENABLE_BINDINGS_VALA=ON -DFLAVOUR_GTK3=OFF -DFLAVOUR_GTK2=ON
    popd
build      : |
    pushd gtk3
        %ninja_build
    popd
    pushd gtk2
        %ninja_build
    popd
install    : |
    pushd gtk3
        %ninja_install
    popd
    pushd gtk2
        %ninja_install
    popd

    # libayatana provides ABI compatibility with libappindicator.
    # Create symlinks with libappindicator's sonames so that closed-source
    # applications built for libappindicator can continue to work.
    pushd $installdir/%libdir%
        for f in *.so*; do
            ln -s $f $(sed 's|ayatana-||' <<< $f)
        done
    popd
